### ISSUE TITLE
the import libraries should be well-organized

### ISSUE THREAD

**Issue by zhixuanli** [kasvii/PMCE#5]
Hi, thanks for your well work and your open-source code.

I have download the code and opened in PyCharm.
However, the codes in the head of many files for import is not correct. Such as in `train.py`:
```
from funcs_utils import save_checkpoint, check_data_pararell, count_parameters
from core.config import cfg, update_config
```

And these import cannot be recognized. If I add the `lib.` in front of each line, it will work. These problems are so many. Could it be work normally? I cannot verify by training now, since the download speed from OneDrive is too slow. Therefore, my second request is could you please add a share link from AliyunPan. 

Thanks again for your code!

**Comment by kasvii** [comment]
1. Yes, it can work since the libraries have been import [here](https://github.com/kasvii/PMCE/blob/main/main/__init_path.py). As I know, some people have successfully reproduced it. Please check you run the code under ./PMCE if using the terminal or check your path includes ./PMCE if you using the debug mode.
2. It's a good idea. Once I upload it, I will tell you. And please wait maybe a week.

**Comment by zhixuanli** [comment]
Thanks for your nice response : )

**Comment by kasvii** [comment]
Hello, the Aliyun link is [https://www.aliyundrive.com/s/FbS9EYuJU9h](https://www.aliyundrive.com/s/FbS9EYuJU9h).

**Comment by zhixuanli** [comment]
Thanks for your sharing!
